

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  # mariadb:
  #   name: mariadb
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: '/home/mshereme/data/mariadb'
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mshereme/data/wordpress'

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    networks: 
      - inception
    volumes:
      - wordpress:/var/www/html/
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html/